name: Node.js Checks and Deploy

on:
  push:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test and build with node 16.x
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm test
    - run: npm run build
    - run: npm prune --production
    - run: curl -sfL https://install.goreleaser.com/github.com/tj/node-prune.sh | bash -s -- -b /usr/local/bin
    - run: /usr/local/bin/node-prune
    
    - name: Deploy
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "docked19"
        heroku_email: ${{secrets.EMAIL}}
        usedocker: true