name: Node.js Checks and Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test and build with node 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x  
    
    - name: Install
      run: npm ci
      
    - name: Test
      run: npm test
      env: 
        OPENWEATHER_KEY: ${{secrets.OPENWEATHER_KEY}}
      
    - name: Build
      run: >- 
       npm run build && npm prune --production &&
       curl -sfL https://install.goreleaser.com/github.com/tj/node-prune.sh | bash -s -- -b . &&
       ./node-prune
    
    - name: Deploy
      run: >-
       HEROKU_API_KEY=${{secrets.HEROKU_API_KEY}} heroku container:login &&
       HEROKU_API_KEY=${{secrets.HEROKU_API_KEY}} heroku container:push web -a ${{secrets.HEROKU_APP}} &&
       HEROKU_API_KEY=${{secrets.HEROKU_API_KEY}} heroku container:release web -a ${{secrets.HEROKU_APP}}
