name: Node.js Checks and Deploy

on:
  push:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test and build with node 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x  
    - run: npm ci
    - run: npm test
    - run: npm run build
    - run: npm prune --production
    - run: curl -sfL https://install.goreleaser.com/github.com/tj/node-prune.sh | bash -s -- -b $HOME/bin
    - run: $HOME/bin/node-prune
    - run: HEROKU_API_KEY=${{secrets.HEROKU_API_KEY}} heroku container:login
    - run: HEROKU_API_KEY=${{secrets.HEROKU_API_KEY}} heroku container:push web -a docked19
    - run: HEROKU_API_KEY=${{secrets.HEROKU_API_KEY}} heroku container:release web -a docked19

