name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy
      run: >-
       HEROKU_API_KEY=${{secrets.HEROKU_API_KEY}} heroku container:login &&
       HEROKU_API_KEY=${{secrets.HEROKU_API_KEY}} heroku container:push web -a ${{secrets.HEROKU_APP}} &&
       HEROKU_API_KEY=${{secrets.HEROKU_API_KEY}} heroku container:release web -a ${{secrets.HEROKU_APP}}
